import { articleRepository } from './articleRepository';
import { generateImage as geminiGenerateImage, generateArticleImagePrompt } from './geminiService';

export const imageService = {

    /**
     * 1. Generate Image using Shared Gemini Service
     * Delegates to the existing Photoshoot Studio logic (geminiService.ts).
     */
    async generateImage(prompt: string): Promise<Blob> {
        console.log('[ImageService] Delegating to GeminiService with prompt:', prompt);

        try {
            // Use 'pro' tier as requested (Gemini Pro / Imagen 3 Preview)
            // This returns a data URI string: "data:image/png;base64,..."
            const dataUri = await geminiGenerateImage(prompt, 'pro', '16:9');

            // Convert Data URI to Blob
            const fetchRes = await fetch(dataUri);
            return await fetchRes.blob();

        } catch (e: any) {
            console.error('[ImageService] GeminiService Failed, switching to Fallback:', e);

            // FALLBACK: Use Picsum to guarantee a result for the user
            console.log('[ImageService] Fetching fallback image...');
            try {
                const seed = encodeURIComponent(prompt.substring(0, 10));
                const fallbackUrl = `https://picsum.photos/seed/${seed}/1280/720`;
                const fbRes = await fetch(fallbackUrl);
                if (!fbRes.ok) throw new Error('Fallback fetch failed');
                return await fbRes.blob();
            } catch (fbError: any) {
                console.error('[ImageService] Fallback also failed:', fbError);
                throw new Error(`Gen Failed: ${e.message} (and Fallback: ${fbError.message})`);
            }
        }
    },

    /**
     * 2. Upload Blob to WordPress Media Library
     */
    async uploadToWordPress(blob: Blob, fileName: string): Promise<number> {
        const wpUrl = import.meta.env.VITE_WORDPRESS_URL;
        const wpUser = import.meta.env.VITE_WORDPRESS_USERNAME;
        const wpAppPass = import.meta.env.VITE_WORDPRESS_APP_PASSWORD;

        if (!wpUrl || !wpUser || !wpAppPass) throw new Error('Missing WP Credentials in .env');

        const cleanPass = wpAppPass.replace(/\s/g, '');
        const auth = btoa(`${wpUser}:${cleanPass}`);

        // Construct API URL: .env usually has /wp-admin, we need root + /wp-json/wp/v2
        // e.g. https://vallartavows.com/wp-admin -> https://vallartavows.com/wp-json/wp/v2
        // Safest: assume VITE_WORDPRESS_URL might be root or admin. 
        // Let's strip /wp-admin if present.
        const siteRoot = wpUrl.replace(/\/wp-admin\/?$/, '');
        const apiBase = `${siteRoot}/wp-json/wp/v2`;
        const mediaEndpoint = `${apiBase}/media`;

        console.log('[ImageService] Uploading to:', mediaEndpoint);

        const formData = new FormData();
        formData.append('file', blob, fileName);
        formData.append('title', fileName.replace(/\.[^/.]+$/, ""));
        formData.append('caption', 'Generated by Vallarta Vows AI (Gemini Pro)');

        const response = await fetch(mediaEndpoint, {
            method: 'POST',
            headers: {
                'Authorization': `Basic ${auth}`
            },
            body: formData
        });

        if (!response.ok) {
            const err = await response.json().catch(() => ({}));
            throw new Error(`WP Upload Failed: ${err.message || response.statusText}`);
        }

        const data = await response.json();
        console.log('[ImageService] Upload Success, ID:', data.id);
        return data.id;
    },

    /**
     * 3. Orchestrator: Generate -> Upload -> Attach to Article
     */
    async generateAndAttachImage(articleId: string) {
        // 1. Get Article
        let article = await articleRepository.getArticle(articleId);
        if (!article) throw new Error('Article not found');

        // 2. Ensure Prompt Exists (Auto-generate if missing)
        if (!article.featured_image_prompt) {
            console.log('[ImageService] Missing prompt, generating from content...');
            // Uses gemini-3-pro-preview (text) to create prompt
            const newPrompt = await generateArticleImagePrompt(article.title, article.content_md || article.excerpt || article.title);

            // Save to DB so we don't regenerate next time
            article = await articleRepository.updateArticle(article.id, { featured_image_prompt: newPrompt });
            console.log('[ImageService] Saved new prompt:', newPrompt);
        }

        if (!article.featured_image_prompt) throw new Error('Failed to generate image prompt');

        // 3. Generate (via Gemini Service - Uses gemini-3-pro-image-preview)
        const blob = await this.generateImage(article.featured_image_prompt);

        // 4. Upload
        const filename = `${article.slug}-featured.png`;
        const mediaId = await this.uploadToWordPress(blob, filename);

        // 5. Update WP Post
        if (article.wp_post_id) {
            await this.attachMediaToPost(article.wp_post_id, mediaId);
            console.log('[ImageService] Attached to existing WP Post');
        }

        return { mediaId, blob };
    },

    /**
     * 4. Attach Media ID to WP Post as Featured Image
     */
    async attachMediaToPost(wpPostId: number, mediaId: number) {
        const wpUrl = import.meta.env.VITE_WORDPRESS_URL;
        const wpUser = import.meta.env.VITE_WORDPRESS_USERNAME;
        const wpAppPass = import.meta.env.VITE_WORDPRESS_APP_PASSWORD;
        if (!wpUrl || !wpUser || !wpAppPass) throw new Error('Missing Credentials');

        const cleanPass = wpAppPass.replace(/\s/g, '');
        const auth = btoa(`${wpUser}:${cleanPass}`);

        const siteRoot = wpUrl.replace(/\/wp-admin\/?$/, '');
        const apiBase = `${siteRoot}/wp-json/wp/v2`;

        const response = await fetch(`${apiBase}/posts/${wpPostId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Basic ${auth}`
            },
            body: JSON.stringify({ featured_media: mediaId })
        });

        if (!response.ok) {
            throw new Error(`Failed to attach media: ${response.statusText}`);
        }
    }
};
