import { useState, useEffect } from 'react';
import { ClipboardDocumentIcon } from '@heroicons/react/24/outline';

const tabs = ['Preview', 'Backend (GAS)', 'Frontend (WordPress)'];

export default function WordPressFormGenerator() {
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied] = useState(false);
  const [webAppUrl, setWebAppUrl] = useState(import.meta.env.VITE_GOOGLE_WEB_APP_URL || '');
  const [supabaseUrl, setSupabaseUrl] = useState(import.meta.env.VITE_SUPABASE_URL || '');
  const [supabaseKey, setSupabaseKey] = useState(import.meta.env.VITE_SUPABASE_ANON_KEY || '');




  // --- Backend Code (Provided by User) ---
  const backendCode = `
function doPost(e) {
  var lock = LockService.getScriptLock();
  // Wait for up to 10 seconds for other processes to finish.
  lock.tryLock(10000);

  try {
    var data = JSON.parse(e.postData.contents);

    // --- FEATURE 1: GENERATE & SAVE PORTRAIT (SERVER-SIDE) ---
    // Generates a portrait using Gemini API and saves directly to Drive
    if (data.type === "generate_portrait") {
      // 1. CONFIGURATION (User must set this for server-side generation)
      var apiKey = "AIzaSyBgoTzidocdKYKB0VKaOl4cR04DgZFOo_4"; 
      var model = "gemini-3-pro-image-preview";
      var apiUrl = "https://generativelanguage.googleapis.com/v1beta/models/" + model + ":generateContent?key=" + apiKey;

      // 2. BUILD PROMPT & PAYLOAD
      var parts = [];
      // Handle Reference Images (Base64)
      if (data.reference_images && Array.isArray(data.reference_images)) {
        data.reference_images.forEach(function(b64) {
           parts.push({
             inlineData: {
               mimeType: "image/png",
               data: b64
             }
           });
        });
      }
      // Add Text Prompt
      var prompt = "Portrait of Robin Manoogian in a " + (data.environment || "Modern Office") + " setting. Professional, approachable, luxury aesthetic.";
      parts.push({ text: prompt });

      var payload = {
        contents: [{ parts: parts }]
      };

      // 3. CALL GEMINI API
      var options = {
        method: "post",
        contentType: "application/json",
        payload: JSON.stringify(payload),
        muteHttpExceptions: true
      };
      
      var response = UrlFetchApp.fetch(apiUrl, options);
      var json = JSON.parse(response.getContentText());

      if (json.error) {
        throw new Error("Gemini API Error: " + json.error.message);
      }

      // 4. EXTRACT IMAGE
      var imageBase64 = null;
      var candidates = json.candidates || [];
      if (candidates.length > 0 && candidates[0].content && candidates[0].content.parts) {
         candidates[0].content.parts.forEach(function(part) {
            if (part.inlineData) imageBase64 = part.inlineData.data;
         });
      }
      
      if (!imageBase64) throw new Error("No image data returned from API.");

      // 5. SAVE TO DRIVE (Using Robin's Convention)
      var folderName = "Vallarta Vows Assets";
      var folders = DriveApp.getFoldersByName(folderName);
      var folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(folderName);

      // Filename convention: robin-manogian-XX.png
      var suffix = new Date().getTime().toString().substr(-6); 
      var fileName = "robin-manogian-" + suffix + ".png";

      var imageBlob = Utilities.newBlob(Utilities.base64Decode(imageBase64), "image/png", fileName);
      var file = folder.createFile(imageBlob);
      file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

      return ContentService.createTextOutput(JSON.stringify({
        "result": "success",
        "url": file.getUrl(),
        "filename": fileName
      })).setMimeType(ContentService.MimeType.JSON);
    }

    // --- FEATURE 2: SAVE IMAGE (CLIENT-SIDE GENERATED) ---
    // Handles saving images generated by the React Frontend
    if (data.type === "save_image") {
      var folderName = "Vallarta Vows Assets";
      var folders = DriveApp.getFoldersByName(folderName);
      var folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(folderName);

      // Filename convention: robin-manogian-XX.png
      var suffix = new Date().getTime().toString().substr(-6); 
      var fileName = "robin-manogian-" + suffix + ".png";

      // Decode and save
      var imageBlob = Utilities.newBlob(Utilities.base64Decode(data.image_data), "image/png", fileName);
      var file = folder.createFile(imageBlob);
      
      file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

      return ContentService.createTextOutput(JSON.stringify({
        "result": "success",
        "url": file.getUrl(),
        "filename": fileName
      })).setMimeType(ContentService.MimeType.JSON);
    }

    // --- FEATURE 3: SEND TEST EMAIL (MARKETING STUDIO) ---
    if (data.type === "send_email") {
      MailApp.sendEmail({
        to: data.to,
        subject: data.subject,
        htmlBody: data.htmlBody
      });
      return ContentService.createTextOutput(JSON.stringify({ "result": "success" }))
        .setMimeType(ContentService.MimeType.JSON);
    }
    // --- FEATURE 4: FREEPIK IMAGE GENERATION PROXY ---
    if (data.type === "generate_image") {
        var apiKey = "FPSX17abaa5b406a98a9720ff384156e60a2"; // Hardcoded for GAS Proxy simplicity, or use PropertiesService
        var endpoint = data.endpoint || "https://api.freepik.com/v1/ai/mystic";
        
        var options = {
            "method": "post",
            "headers": {
                "Content-Type": "application/json",
                "x-freepik-api-key": apiKey,
                "Accept": "application/json"
            },
            "payload": JSON.stringify(data.payload),
            "muteHttpExceptions": true
        };

        try {
            var response = UrlFetchApp.fetch(endpoint, options);
            var responseCode = response.getResponseCode();
            var responseBody = response.getContentText();
            var json = JSON.parse(responseBody);

            // --- HANDLE ASYNC TASKS (FLUX / MYSTIC) ---
            // If Freepik returns a task_id, we must poll for the result.
            if (json.task_id) {
                 var taskId = json.task_id;
                 var statusUrl = endpoint + "/" + taskId; // Convention: GET endpoint/{id}
                 
                 // Polling Loop (Max 30 attempts * 2 sec = 60 sec timeout)
                 for (var i = 0; i < 30; i++) {
                     Utilities.sleep(2000); // Wait 2 seconds
                     
                     var statusOptions = {
                         "method": "get",
                         "headers": {
                             "x-freepik-api-key": apiKey,
                             "Accept": "application/json"
                         },
                         "muteHttpExceptions": true
                     };
                     
                     var statusResp = UrlFetchApp.fetch(statusUrl, statusOptions);
                     var statusJson = JSON.parse(statusResp.getContentText());
                     
                     if (statusJson.status === "COMPLETED") {
                         // Task Done! Return the result
                         return ContentService.createTextOutput(JSON.stringify({
                             "result": "success",
                             "data": statusJson // Contains { data: [{ url: ... }] }
                         })).setMimeType(ContentService.MimeType.JSON);
                     }
                     
                     if (statusJson.status === "FAILED") {
                         throw new Error("Async Generation Failed: " + JSON.stringify(statusJson));
                     }
                     // If "PENDING" or "IN_PROGRESS", continue loop
                 }
                 throw new Error("Timeout waiting for async image generation.");
            }

            // Sync Response (Classic Fast, etc)
            return ContentService.createTextOutput(JSON.stringify({
                "result": responseCode === 200 ? "success" : "error",
                "code": responseCode,
                "data": json
            })).setMimeType(ContentService.MimeType.JSON);

        } catch (e) {
            return ContentService.createTextOutput(JSON.stringify({
                "result": "error",
                "message": e.toString()
            })).setMimeType(ContentService.MimeType.JSON);
        }
    }
    
    // --- FEATURE 3: WEDDING INQUIRY FORM (DEFAULT) ---
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    
    // --- LOGIC ENGINE ---
    // Calculate simple estimate based on luxury averages
    var guestCount = parseInt(data.guest_count) || 0;
    var villaBase = 15000;
    var cateringBase = 300; // per person
    var estimatedCatering = guestCount * cateringBase;
    var totalBase = villaBase + estimatedCatering;

    // Flatten services array
    var services = data.services ? data.services.join(", ") : "Full Planning";

    // --- SAVE TO SHEET ---
    var status = "New Lead"; // Initial CRM Status
    var timestamp = new Date();

    // Prepare row data (Customize column order to match your Sheet)
    var rowData = [
      timestamp,  // Timestamp (Column A)
      data.partner1_first_name,
      data.partner1_last_name,
      data.partner1_gender, // Partner 1 Gender
      data.partner2_first_name,
      data.partner2_last_name,
      data.partner2_gender, // Partner 2 Gender
      data.email,
      "'" + data.phone, // Force string format for phone
      data.wedding_date,
      data.guest_count,
      data.budget_range,
      data.location_preference,
      data.referral_source, 
      services, // Services Included
      data.message,
      status // Initial Status (e.g. "New Lead")
    ];

    sheet.appendRow(rowData);

    // --- EMAIL 1: NOTIFICATION TO ROBIN ---
    var adminSubject = "New submission from Vallarta Vows Get In Touch";
    var adminBody = "<h2>New Website Inquiry</h2>" +
      "<p><strong>Couple:</strong> " + data.partner1_first_name + " (" + (data.partner1_gender || "N/A") + ") & " + data.partner2_first_name + " (" + (data.partner2_gender || "N/A") + ")</p>" +
      "<p><strong>Email:</strong> " + data.email + "</p>" +
      "<p><strong>Phone:</strong> " + data.phone + "</p>" +
      "<p><strong>Date:</strong> " + data.wedding_date + "</p>" +
      "<p><strong>Guests:</strong> " + guestCount + "</p>" +
      "<p><strong>Their Budget:</strong> " + data.budget_range + "</p>" +
      "<p><strong>System Estimate:</strong> $" + totalBase.toLocaleString() + "</p>" +
      "<p><strong>Services:</strong> " + services + "</p>" +
      "<p><strong>Referral Source:</strong> " + data.referral_source + "</p>" +
      "<p><strong>Message:</strong><br>" + data.message + "</p>";

    MailApp.sendEmail({
      to: "robin@vallartavows.com",
      subject: adminSubject,
      htmlBody: adminBody
    });



    return ContentService.createTextOutput(JSON.stringify({ "result": "success" }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (e) {
    // Send Error Email to Admin
    MailApp.sendEmail({
      to: "info@vallartavows.com",
      subject: "URGENT: Website Form Error",
      htmlBody: "<h2>Form Submission Failed</h2>" + 
                "<p><strong>Error:</strong> " + e.toString() + "</p>" +
                "<p><strong>Stack:</strong> " + e.stack + "</p>" +
                "<p><strong>Payload:</strong> <br>" + (e.postData ? e.postData.contents : "No Post Data") + "</p>"
    });

    return ContentService.createTextOutput(JSON.stringify({ "result": "error", "error": e.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  } finally {
    lock.releaseLock();
  }
}
  `.trim();

  // --- Frontend Code (HTML/JS) ---
  const frontendCode = `
<!-- Vallarta Vows Lead Form: Multi-Step Wizard -->
<div id="vv-contact-form" class="vv-form-container">
  
  <!-- Progress Bar -->
  <div class="vv-progress-container">
     <div class="vv-progress-bar" id="vvProgressBar"></div>
  </div>
  <div class="vv-step-indicator">
      <span class="active">Step 1: The Couple</span>
      <span>Step 2: The Big Day</span>
      <span>Step 3: Vision</span>
  </div>

  <form id="vvContactForm">
    
    <!-- STEP 1: The Couple -->
    <div class="vv-step" id="vvStep1">
        <h3 class="vv-section-title">The Couple</h3>
        <div class="vv-grid-2">
          <div class="vv-group">
            <label>Partner 1 First Name <span class="vv-required">*</span></label>
            <input type="text" name="partner1_first_name" required placeholder="First Name" />
          </div>
          <div class="vv-group">
            <label>Partner 1 Last Name <span class="vv-required">*</span></label>
            <input type="text" name="partner1_last_name" required placeholder="Last Name" />
          </div>
        </div>
        <div class="vv-group">
            <label>Partner 1 Gender / Pronouns <span class="vv-required">*</span></label>
            <select name="partner1_gender" required>
              <option value="Bride">Bride</option>
              <option value="Groom">Groom</option>
              <option value="Non-Binary">Non-Binary / They</option>
            </select>
        </div>

        <div class="vv-grid-2">
          <div class="vv-group">
            <label>Partner 2 First Name <span class="vv-required">*</span></label>
            <input type="text" name="partner2_first_name" required placeholder="First Name" />
          </div>
          <div class="vv-group">
            <label>Partner 2 Last Name <span class="vv-required">*</span></label>
            <input type="text" name="partner2_last_name" required placeholder="Last Name" />
          </div>
        </div>
        <div class="vv-group">
            <label>Partner 2 Gender / Pronouns <span class="vv-required">*</span></label>
            <select name="partner2_gender" required>
              <option value="Groom">Groom</option>
              <option value="Bride">Bride</option>
              <option value="Non-Binary">Non-Binary / They</option>
            </select>
        </div>

        <div class="vv-nav-buttons">
           <button type="button" class="vv-btn-next" onclick="vvNextStep(1)">Next Step &rarr;</button>
        </div>
    </div>

    <!-- STEP 2: The Big Day -->
    <div class="vv-step" id="vvStep2" style="display:none;">
        <h3 class="vv-section-title">The Big Day</h3>
        <div class="vv-grid-2">
            <div class="vv-group">
              <label>Wedding Date (Est.) <span class="vv-required">*</span></label>
              <input type="date" name="wedding_date" required />
            </div>
            <div class="vv-group">
              <label>Guest Count <span class="vv-required">*</span></label>
              <input type="number" name="guest_count" placeholder="e.g. 50" required />
            </div>
        </div>
        <div class="vv-grid-2">
            <div class="vv-group">
              <label>Budget Range (USD) <span class="vv-required">*</span></label>
              <select name="budget_range" required>
                <option>$ 1,500 - $ 5,000</option>
                <option>$ 5,000 - $ 10,000</option>
                <option>$ 10,000 - $ 20,000</option>
                <option>$ 20,000 - $ 30,000</option>
                <option>$ 30,000 - $ 40,000</option>
                <option>$ 40,000 - $ 50,000</option>
                <option>$ 50,000 - $ 60,000</option>
                <option>$ 60,000 - $ 70,000</option>
                <option>$ 70,000 - $ 80,000</option>
                <option>$ 80,000 - $ 90,000</option>
                <option>$ 90,000 - $ 100,000</option>
                <option>$ 100,000+</option>
              </select>
            </div>
            <div class="vv-group">
              <label>Location Preference <span class="vv-required">*</span></label>
              <select name="location_preference" required>
                  <option>Beachfront</option>
                  <option>Garden / Jungle</option>
                  <option>Private Villa</option>
                  <option>Resort Ballrom</option>
              </select>
            </div>
        </div>
        <div class="vv-group">
           <label>Referral Source <span class="vv-required">*</span></label>
           <select name="referral_source" required>
              <option>Instagram</option>
              <option>Google Search</option>
              <option>Wedding Wire / The Knot</option>
              <option>Friend / Family</option>
              <option>Other</option>
           </select>
        </div>

        <div class="vv-nav-buttons">
           <button type="button" class="vv-btn-back" onclick="vvPrevStep(2)">&larr; Back</button>
           <button type="button" class="vv-btn-next" onclick="vvNextStep(2)">Next Step &rarr;</button>
        </div>
    </div>

    <!-- STEP 3: Contact & Vision -->
    <div class="vv-step" id="vvStep3" style="display:none;">
         <!-- Contact Info -->
         <h3 class="vv-section-title">Contact</h3>
         <div class="vv-grid-2">
           <div class="vv-group">
             <label>Email Address <span class="vv-required">*</span></label>
             <input type="email" name="email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" placeholder="name@example.com" />
           </div>
           <div class="vv-group">
             <label>Phone Number <span class="vv-required">*</span></label>
             <input type="tel" name="phone" required />
           </div>
         </div>

         <!-- Honeypot -->
         <div style="display:none !important; visibility:hidden; opacity:0; height:0;">
            <label>Website URL</label>
            <input type="text" name="website_url" tabindex="-1" autocomplete="off" />
         </div>

         <h3 class="vv-section-title">Services & Vision</h3>
         <div class="vv-checkbox-grid">
            <label><input type="checkbox" name="service" value="Ceremony" /> Ceremony</label>
            <label><input type="checkbox" name="service" value="Reception" /> Reception</label>
            <label><input type="checkbox" name="service" value="Catering" /> Catering</label>
            <label><input type="checkbox" name="service" value="Photography" /> Photography</label>
            <label><input type="checkbox" name="service" value="Florals" /> Florals</label>
            <label><input type="checkbox" name="service" value="Music" /> Music / DJ</label>
         </div>

         <div class="vv-group">
             <label>Message / Vision</label>
             <textarea name="message" rows="3" placeholder="Tell us about your dream wedding..."></textarea>
         </div>

         <div class="vv-nav-buttons">
            <button type="button" class="vv-btn-back" onclick="vvPrevStep(3)">&larr; Back</button>
            <button type="submit" id="vvSubmitBtn">Send Inquiry</button>
         </div>
         <p id="vvFormStatus" style="display:none; margin-top:10px; font-weight:bold; text-align:center;"></p>
    </div>

  </form>
</div>

<script>
  // Global Step Functions
  window.vvNextStep = function(currentStep) {
      if(!validateStep(currentStep)) return;
      document.getElementById('vvStep' + currentStep).style.display = 'none';
      document.getElementById('vvStep' + (currentStep + 1)).style.display = 'block';
      updateProgress(currentStep + 1);
  };
  window.vvPrevStep = function(currentStep) {
      document.getElementById('vvStep' + currentStep).style.display = 'none';
      document.getElementById('vvStep' + (currentStep - 1)).style.display = 'block';
      updateProgress(currentStep - 1);
  };

  function updateProgress(step) {
      const bar = document.getElementById('vvProgressBar');
      const indicators = document.querySelectorAll('.vv-step-indicator span');
      indicators.forEach((ind, idx) => {
          if (idx < step - 1) ind.className = 'completed'; // optional style
          else if (idx === step - 1) ind.className = 'active';
          else ind.className = '';
      });
      // 3 steps total
      let width = '33%';
      if(step === 2) width = '66%';
      if(step === 3) width = '100%';
      bar.style.width = width;
  }

  function validateStep(step) {
      const container = document.getElementById('vvStep' + step);
      const inputs = container.querySelectorAll('input[required], select[required]');
      let valid = true;
      inputs.forEach(input => {
          if (!input.value) {
              valid = false;
              input.style.borderColor = '#dc2626';
              // Simple shake effect
              input.style.animation = 'vvShake 0.3s';
              setTimeout(() => input.style.animation = '', 300);
          } else {
              input.style.borderColor = '#e5e7eb';
          }
           // Special check for Email on Step 3 (though usually checking on step exit is good)
           if (input.type === 'email' && input.value && !input.checkValidity()) {
               valid = false;
               alert('Please enter a valid email.');
               input.style.borderColor = '#dc2626';
           }
      });
      return valid;
  }

  (function() {
    const scriptURL = '${webAppUrl || 'YOUR_GOOGLE_WEB_APP_URL_HERE'}';
    const supabaseUrl = '${supabaseUrl.replace(/\/$/, '') || 'YOUR_SUPABASE_URL_HERE'}';
    const form = document.getElementById('vvContactForm');
    const statusMsg = document.getElementById('vvFormStatus');
    const btn = document.getElementById('vvSubmitBtn');

    if (!form || form.getAttribute('data-bound')) return;
    form.setAttribute('data-bound', 'true');
    
    form.addEventListener('submit', e => {
      e.preventDefault();
      
       // Honeypot Check
      const honeypot = form.querySelector('input[name="website_url"]');
      if (honeypot && honeypot.value) return; 

      if(supabaseUrl.includes('YOUR_SUPABASE')) console.warn('Supabase not configured.');

      btn.innerText = 'Sending...';
      btn.disabled = true;
      statusMsg.style.display = 'none';

      // Build Data
      const formData = new FormData(form);
      const data = {};
      formData.forEach((value, key) => { if(key!=='service') data[key] = value; });
      
      const services = [];
      form.querySelectorAll('input[name="service"]:checked').forEach(cb => services.push(cb.value));
      data.services = services;
      data.type = "wedding_inquiry";

      // 1. GAS Submission
      fetch(scriptURL, { 
          method: 'POST', body: JSON.stringify(data), mode: 'no-cors',
          headers: { 'Content-Type': 'text/plain' }
      })
      .then(() => {
           statusMsg.innerText = "Sent! We'll be in touch soon.";
           statusMsg.style.color = 'green';
           statusMsg.style.display = 'block';
           btn.innerText = 'Sent!';
           form.reset();
           setTimeout(() => { // Reset to step 1
               window.location.reload(); // Easiest way to reset wizard state
           }, 3000);
      })
      .catch(err => {
           console.error(err);
           statusMsg.innerText = "Error. Please email us.";
           statusMsg.style.color = 'red';
           statusMsg.style.display = 'block';
           btn.disabled = false;
      });

      const supabaseKey = '${supabaseKey || 'YOUR_SUPABASE_KEY_HERE'}';
      if(!supabaseUrl.includes('YOUR_SUPABASE')) {
          const supabaseData = { ...data, status: 'New', services_needed: services };
          delete supabaseData.service; 
          delete supabaseData.type;
          delete supabaseData.services; // Remove auxiliary field not in DB
          delete supabaseData.website_url; // Remove honeypot field not in DB
          
          if(supabaseData.guest_count) supabaseData.guest_count = parseInt(supabaseData.guest_count);
          if(!supabaseData.wedding_date) supabaseData.wedding_date = null;

          // Attempt Insert
          fetch(supabaseUrl + '/rest/v1/leads', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
                  'apikey': supabaseKey,
                  'Authorization': 'Bearer ' + supabaseKey,
                  'Prefer': 'return=minimal'
              },
              body: JSON.stringify(supabaseData)
          })
          .then(async response => {
             if (!response.ok) {
                 const errText = await response.text();
                 throw new Error('DB Error: ' + errText);
             }
             console.log('Saved to Supabase');
          })
          .catch(err => {
              console.error('Supabase Sync Failed:', err);
          });
      }
    });
  })();
</script>

<style>
  /* Animations */
  @keyframes vvFadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
  @keyframes vvShake { 0% { transform: translateX(0); } 25% { transform: translateX(-5px); } 50% { transform: translateX(5px); } 100% { transform: translateX(0); } }

  .vv-form-container { 
    padding: 40px; 
    background: #fff;
    background: linear-gradient(135deg, #fff 0%, #fff1f2 100%);
    border-radius: 20px; 
    font-family: 'Poppins', sans-serif;
    max-width: 600px;
    margin: 0 auto;
    box-shadow: 0 20px 40px -10px rgba(219, 39, 119, 0.2);
    animation: vvFadeIn 0.6s ease-out forwards;
    position: relative;
    overflow: hidden;
  }
  
  /* Progress Bar */
  .vv-progress-container { width: 100%; background: #fce7f3; height: 6px; border-radius: 3px; margin-bottom: 30px; overflow: hidden; }
  .vv-progress-bar { height: 100%; background: #db2777; width: 33%; transition: width 0.4s ease; }
  
  .vv-step-indicator { display: flex; justify-content: space-between; margin-bottom: 25px; font-size: 0.85rem; color: #9ca3af; font-weight: 500; }
  .vv-step-indicator span.active { color: #db2777; font-weight: 700; transform: scale(1.05); transition: transform 0.2s; }

  .vv-step { animation: vvFadeIn 0.4s ease-out; }

  .vv-section-title {
    font-family: 'Cormorant Garamond', serif;
    font-size: 1.8rem;
    color: #db2777; 
    margin-bottom: 25px;
    text-align: center;
  }
  
  .vv-grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }
  @media (max-width: 600px) { .vv-grid-2 { grid-template-columns: 1fr; gap: 15px; } }
  
  .vv-group { margin-bottom: 20px; }
  .vv-required { color: #dc2626; font-weight: bold; margin-left: 2px; }

  .vv-group label { 
      display: block; margin-bottom: 8px; font-weight: 500; font-size: 0.95rem; color: #374151; 
  }

  .vv-group input, .vv-group select, .vv-group textarea { 
    width: 100%; padding: 14px 16px; 
    border: 1px solid #e5e7eb; border-radius: 10px; 
    font-size: 1rem;
    background: #f9fafb;
    transition: all 0.3s;
  }

  .vv-group input:focus, .vv-group select:focus, .vv-group textarea:focus { 
      outline: none; 
      border-color: #db2777; 
      background: #fff;
      box-shadow: 0 0 0 4px rgba(219, 39, 119, 0.1); 
  }
  
  .vv-checkbox-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 30px; }
  .vv-checkbox-grid label { 
      display: flex; items-center; gap: 10px; font-size: 0.95rem; color: #4b5563; 
      cursor: pointer; padding: 10px; border: 1px solid #f3f4f6; border-radius: 8px; transition: all 0.2s;
  }
  .vv-checkbox-grid label:hover { border-color: #fbcfe8; background: #fff1f2; }
  .vv-checkbox-grid input[type="checkbox"] { width: auto; accent-color: #db2777; margin: 0; }
  
  .vv-nav-buttons { display: flex; justify-content: space-between; margin-top: 30px; gap: 15px; }
  .vv-nav-buttons button { flex: 1; padding: 14px; border-radius: 8px; border: none; font-weight: 600; cursor: pointer; transition: transform 0.2s; font-size: 1rem; }
  
  .vv-btn-back { background: #f3f4f6; color: #4b5563; }
  .vv-btn-back:hover { background: #e5e7eb; }
  
  .vv-btn-next, #vvSubmitBtn { background: #db2777; color: white; box-shadow: 0 4px 10px rgba(219, 39, 119, 0.3); }
  .vv-btn-next:hover, #vvSubmitBtn:hover { background: #be185d; transform: translateY(-2px); box-shadow: 0 6px 15px rgba(219, 39, 119, 0.4); }
  
  #vvSubmitBtn { background: linear-gradient(135deg, #db2777 0%, #9d174d 100%); }
</style>
  `.trim();

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-6xl mx-auto h-[calc(100vh-140px)] flex flex-col">
      <div className="mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-serif font-bold text-primary">Form Generator</h1>
          <p className="text-secondary">Deploy "Lead Scoring" ready forms to WordPress.</p>
        </div>

        {/* Tab Navigation */}
        <div className="bg-white rounded-lg border border-gray-200 p-1 flex">
          {tabs.map((tab, idx) => (
            <button
              key={tab}
              onClick={() => setActiveTab(idx)}
              className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${activeTab === idx ? 'bg-primary text-white shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Debug Info Panel */}
      <div className="mb-4 p-4 bg-gray-100 rounded border border-gray-300 text-xs font-mono text-gray-600">
        <p><strong>Debug Status:</strong></p>

        <p>Web App URL: {import.meta.env.VITE_GOOGLE_WEB_APP_URL ? 'Loaded' : 'MISSING'}</p>
        <p>Supabase URL: {import.meta.env.VITE_SUPABASE_URL ? 'Loaded' : 'MISSING'}</p>
        <p>Supabase Key: {import.meta.env.VITE_SUPABASE_ANON_KEY ? 'Loaded' : 'MISSING'}</p>
      </div>

      <div className="flex-1 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden flex flex-col">
        {/* TAB 0: PREVIEW */}
        {activeTab === 0 && (
          <div className="flex-1 p-10 flex justify-center items-start bg-gray-50 overflow-y-auto">
            {/* Mocking the WP Form appearance using the exact styles we inject */}
            <div key={Date.now()} style={{ maxWidth: '600px', width: '100%' }}>
              <div className="bg-white p-4 mb-4 rounded border border-yellow-200 bg-yellow-50 text-yellow-800 text-sm">
                <strong>Preview Mode:</strong> This is exactly how the form will appear on vallartavows.com.
              </div>
              <div dangerouslySetInnerHTML={{ __html: frontendCode }} />
              <ScriptRunner code={frontendCode} />
            </div>
          </div>
        )}

        {/* TAB 1 & 2: CODE */}
        {(activeTab === 1 || activeTab === 2) && (
          <div className="flex-1 flex flex-col">
            <div className="bg-gray-800 text-gray-200 px-4 py-3 text-sm font-mono border-b border-gray-700 flex justify-between items-center sticky top-0">
              <span className="font-semibold text-primary-300">
                {activeTab === 1 ? '1. Google Apps Script (Backend)' : '2. WordPress HTML Block (Frontend)'}
              </span>

              <div className="flex items-center gap-4">
                {activeTab === 2 && (
                  <div className="flex gap-2">
                    <input
                      type="text"
                      placeholder="Google Web App URL"
                      className="bg-gray-700 border border-gray-600 text-white px-3 py-1 rounded text-xs w-48 focus:border-primary focus:outline-none"
                      value={webAppUrl}
                      onChange={(e) => setWebAppUrl(e.target.value)}
                    />
                    {webAppUrl.includes('spreadsheets') && <span className="text-red-400 text-xs flex items-center">Use Script URL, not Sheet URL!</span>}
                    <input
                      type="text"
                      placeholder="Supabase Project URL"
                      className="bg-gray-700 border border-gray-600 text-white px-3 py-1 rounded text-xs w-48 focus:border-primary focus:outline-none"
                      value={supabaseUrl}
                      onChange={(e) => setSupabaseUrl(e.target.value)}
                    />
                    <input
                      type="text"
                      placeholder="Supabase Anon Key"
                      className="bg-gray-700 border border-gray-600 text-white px-3 py-1 rounded text-xs w-48 focus:border-primary focus:outline-none"
                      value={supabaseKey}
                      onChange={(e) => setSupabaseKey(e.target.value)}
                    />
                  </div>
                )}
                <button
                  onClick={() => copyToClipboard(activeTab === 1 ? backendCode : frontendCode)}
                  className="hover:text-white flex items-center gap-1 bg-gray-700 px-3 py-1 rounded hover:bg-gray-600 transition-colors"
                >
                  <ClipboardDocumentIcon className="h-4 w-4" />
                  {copied ? 'Copied!' : 'Copy Code'}
                </button>
              </div>
            </div>
            <textarea
              readOnly
              className="flex-1 w-full bg-[#1e1e1e] text-[#d4d4d4] font-mono text-sm p-4 resize-none focus:outline-none leading-relaxed"
              value={activeTab === 1 ? backendCode : frontendCode}
            />
          </div>
        )}
      </div>
    </div >
  );
}

// Helper component to execute scripts embedded in HTML string
// Helper component to execute scripts embedded in HTML string
function ScriptRunner({ code }: { code: string }) {

  useEffect(() => {
    // Small delay to ensure DOM is ready
    const timer = setTimeout(() => {
      const match = code.match(/<script>([\s\S]*?)<\/script>/);
      if (match && match[1]) {
        try {
          // Dangerous but necessary for "Preview" of raw HTML/JS
          // eslint-disable-next-line
          eval(match[1]);
        } catch (e) {
          console.error("Preview Script Error", e);
        }
      }
    }, 500);

    return () => clearTimeout(timer);
  }, [code]);

  return null;
}
