import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import fetch from 'node-fetch';
import { FormData } from 'formdata-node';
import { fileFromPath } from 'formdata-node/file-from-path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootPath = path.resolve(__dirname, '..');
const envPath = path.join(rootPath, '.env');

console.log('Loading .env from:', envPath);
dotenv.config({ path: envPath });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;
const wpUrl = process.env.VITE_WORDPRESS_URL;
const wpUser = process.env.VITE_WORDPRESS_USERNAME;
const wpAppPass = process.env.VITE_WORDPRESS_APP_PASSWORD;

if (!supabaseUrl || !supabaseKey) {
    console.error("Missing Supabase credentials");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function uploadImageToWP(filePath) {
    if (!wpUrl || !wpUser || !wpAppPass) {
        console.warn("Missing WP credentials, skipping upload. Using local path.");
        return null; // Fallback
    }

    try {
        console.log("Uploading image to WordPress...");
        const cleanPass = wpAppPass.replace(/\s/g, '');
        const auth = Buffer.from(`${wpUser}:${cleanPass}`).toString('base64');

        // Use fixed URL logic
        const siteRoot = wpUrl.replace(/\/wp-admin\/?$/, '').replace(/\/+$/, '');
        const apiBase = `${siteRoot}/wp-json/wp/v2`;
        const mediaEndpoint = `${apiBase}/media`;

        const form = new FormData();
        const file = await fileFromPath(filePath);
        form.append('file', file, 'venues-header.png');
        form.append('title', 'Venues Email Header');
        form.append('caption', 'Generated by Vallarta Vows AI');

        const response = await fetch(mediaEndpoint, {
            method: 'POST',
            headers: {
                'Authorization': `Basic ${auth}`
            },
            body: form
        });

        if (!response.ok) {
            const txt = await response.text();
            throw new Error(`Upload failed: ${response.status} ${txt}`);
        }

        const data = await response.json();
        console.log("Image uploaded successfully:", data.source_url);
        return data.source_url;

    } catch (e) {
        console.error("WP Upload Error:", e);
        return null;
    }
}

const htmlContent = `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: 'Helvetica', sans-serif; background-color: #f9fafb; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
  .header { padding: 0; background-color: #db2777; }
  .header img { width: 100%; height: auto; display: block; }
  .content { padding: 40px; color: #374151; line-height: 1.6; }
  .button { display: inline-block; background-color: #db2777; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold; margin-top: 20px; }
  .section-title { font-size: 18px; font-weight: bold; color: #db2777; margin-top: 25px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
  .venue-card { margin-bottom: 20px; border: 1px solid #eee; border-radius: 8px; overflow: hidden; }
  .venue-img { width: 100%; height: 200px; background-color: #ddd; object-fit: cover; }
  .venue-info { padding: 15px; }
  .venue-name { font-weight: bold; font-size: 16px; margin-bottom: 5px; color: #333; }
  .venue-desc { font-size: 13px; color: #666; }
  .footer { background-color: #f3f4f6; padding: 20px; text-align: center; font-size: 12px; color: #9ca3af; }
</style>
</head>
<body>
  <div class="container">
    <div class="header">
       <!-- Replaced with dynamic image -->
       <img src="{{IMAGE_URL}}" alt="Beautiful Wedding Venues" />
    </div>
    <div class="content">
      <p>Hello [Client Name],</p>
      <p>Finding the perfect venue is the first step to your dream wedding in Puerto Vallarta. 🌴💍</p>
      <p>I have curated a list of my absolute favorite venues that offer stunning views, privacy, and that magical atmosphere you are looking for.</p>
      
      <div class="section-title">📍 Top Beachfront Venues</div>
      
      <div class="venue-card">
        <!-- Placeholder for venue image -->
        <div class="venue-info">
            <div class="venue-name">Martoca Beach Garden</div>
            <div class="venue-desc">A mix of garden and beach, perfect for sunset ceremonies and dancing under the stars.</div>
        </div>
      </div>

      <div class="venue-card">
        <div class="venue-info">
            <div class="venue-name">Hyatt Ziva Main Beach</div>
            <div class="venue-desc">Luxury all-inclusive convenience with a private beach feel.</div>
        </div>
      </div>

      <div class="section-title">🏰 Private Villas</div>
      <p>For a more intimate and exclusive experience, consider a private villa rental.</p>
      
      <p>I would love to walk you through the pros and cons of each.</p>
      
      <a href="[Insert Booking Link]" class="button">Schedule Venue Tour Call</a>
      
      <p>Warm regards,<br>
      <strong>Robin Manoogian</strong><br>
      Vallarta Vows</p>
    </div>
    <div class="footer">
      &copy; 2026 Vallarta Vows. All rights reserved.
    </div>
  </div>
</body>
</html>
`;

async function seed() {
    console.log("Starting Venues Template Seed...");

    // Path to your generated image
    const imagePath = path.join(rootPath, 'public/assets/venues_email_header.png');
    let finalImageUrl = 'http://www.vallartavows.com/wp-content/uploads/2026/01/venues-header-placeholder.png'; // Fallback

    if (fs.existsSync(imagePath)) {
        const uploadedUrl = await uploadImageToWP(imagePath);
        if (uploadedUrl) {
            finalImageUrl = uploadedUrl;
        } else {
            console.log("Using local path fallback (note: won't work in email clients properly)");
            // If we can't upload, maybe use a placeholder or relative if served.
            // But for email, relative is bad.
            // Let's stick to the fallback if upload fails, or maybe the user can replace it.
        }
    } else {
        console.warn("Image file not found at:", imagePath);
    }

    const finalHtml = htmlContent.replace('{{IMAGE_URL}}', finalImageUrl);

    const { data, error } = await supabase
        .from('email_templates')
        .insert({
            id: 'venues-recommendation',
            title: 'Venues Recommendation',
            description: 'Curated list of top wedding venues in Puerto Vallarta.',
            image_url: finalImageUrl,
            html_content: finalHtml,
            updated_at: new Date().toISOString()
        })
        .select();

    if (error) {
        console.error("Error inserting template:", error);
    } else {
        console.log("Success! Template created:", data);
    }
}

seed();
